#liquibase
url=jdbc:postgresql://localhost:5432/cruddb
username=postgres
password=postgres
driver=org.postgresql.Driver
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml

#application
db.url=jdbc:postgresql://localhost:5432/cruddb
db.user=postgres
db.password=postgres
db.driver=org.postgresql.Driver